### ISSUE TITLE
Project doesn't compile without an API Key set

### ISSUE THREAD

**Issue by th0mas** [dwyl/auth_plug#19]
Mix fails to compile the project without an API key set due to the module attributes used in the Demo application. 

Is it possible to set these at runtime to avoid this and allow for some nicer error messages?

**Comment by nelsonic** [comment]
@th0mas it would be great to have better error messages so people don't get stuck if they don't have an API Key. 👍

**Comment by nelsonic** [comment]
@th0mas if you have time to add a friendly error message, please go for it. 🙌

**Comment by nelsonic** [comment]
Added with tests in: https://github.com/dwyl/auth_plug/pull/21 ✅ :shipit:

**Comment by nelsonic** [comment]
Added by @th0mas with tests in: https://github.com/dwyl/auth_plug/pull/21 ✅ :shipit:
