### ISSUE TITLE
Check for `end_session` errors

### ISSUE THREAD

**Issue by SimonLab** [dwyl/auth_plug#38]
At the moment the `end_session` function called in the `logout` function always returns 200 status code:

https://github.com/dwyl/auth_plug/blob/9a52b82e5e1e51f97a70ac9931e636f1fa6f6357/lib/auth_plug.ex#L132-L133

However the
- get request could return an error:
https://github.com/dwyl/auth_plug/blob/9a52b82e5e1e51f97a70ac9931e636f1fa6f6357/lib/auth_plug.ex#L128-L129

- the `parse_body_response` could also fail if the `body` doesn't exists or if `Jason.decode` fails:
https://github.com/dwyl/auth_plug/blob/9a52b82e5e1e51f97a70ac9931e636f1fa6f6357/lib/auth_plug.ex#L103-L108

We can add checks to make sure that all these possible errors are managed on logout

**Comment by nelsonic** [comment]
@SimonLab keen to add this error handling when possible. 🙏

**Comment by SimonLab** [comment]
Looking at this now, so we can close this issue :+1:

**Comment by nelsonic** [comment]
Amaze @SimonLab 🎉

**Comment by SimonLab** [comment]
We first want to make sure `HTTPoison.post` method returns `{:ok, ...}` and not {:error, ...}
see https://hexdocs.pm/httpoison/HTTPoison.html#post/4
![image](https://user-images.githubusercontent.com/6057298/214007715-658bd00d-948f-4830-b619-02d5dddc2795.png)

Then if the post request worked we want to check the returned status code is `200`.

We can test this two steps running `auth_plug` in iex with `iex -S mix`

```iex
HTTPoison.post('wrong-http-address', '')
{:error, %HTTPoison.Error{reason: :nxdomain, id: nil}}

HTTPoison.post('https://mvp.fly.dev', '')
{:ok,
 %HTTPoison.Response{
   status_code: 404,
   body: "Not Found",
   headers: [
     {"cache-control", "max-age=0, private, must-revalidate"},
     {"content-length", "9"},
     {"content-type", "text/html; charset=utf-8"},
     {"date", "Mon, 23 Jan 2023 09:41:20 GMT"},
     {"server", "Fly/38bedbc2 (2023-01-23)"},
     {"x-request-id", "Fzzmwcbo_JnvSWoAABmR"},
     {"via", "1.1 fly.io"},
     {"fly-request-id", "01GQF01VW39T3S9BTH3RYK82YM-lhr"}
   ],
   request_url: "https://mvp.fly.dev",
   request: %HTTPoison.Request{
     method: :post,
     url: "https://mvp.fly.dev",
     headers: [],
     body: [],
     params: %{},
     options: []
   }
 }}
```

The first request returns the tuple `{:error,...}` as the url is not correct/found
The second request returns a 404 status code, the url is correct (the mvp.fly.dev is accessible) however there is no post endpoint defined for `/`

**Comment by nelsonic** [comment]
Thanks again @SimonLab 👍
