### ISSUE TITLE
Create `get_auth_url` public function

### ISSUE THREAD

**Issue by SimonLab** [dwyl/auth_plug#43]
Having a public api to access the auth_url might be useful when the consumer application has only one optional auth route.
In this case we might want to create a link to allow user to login directly from this optional auth page.

For example at the moment in [auth_plug_example]() to login on the optional page we are creating a link to the admin page:
see https://github.com/dwyl/auth_plug_example/blob/8cc2822f013361c48ee63c14c8cc7bcade4973ea/lib/app_web/templates/page/optional.html.eex#L12
```html
try <a href="/admin">login</a>
```

- [x] Create the `get_auth_url\2` function which can takes the connection `conn` and an optional string parameter to let know the auth app where to redirect to after authenticated

I wanted to use this type of function in https://github.com/dwyl/phoenix-liveview-chat-example/issues/15

**Comment by nelsonic** [comment]
@SimonLab thanks for opening this issue. 👍

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/auth_plug/1.4.8 📦
