### ISSUE TITLE
Reponse 200 on logout?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/auth_plug#46]
While using the `logout` function in [phoenix-liveview-chat-example](https://github.com/dwyl/phoenix-liveview-chat-example) I noticed the function set the status code to 200 using the [resp](https://hexdocs.pm/plug/Plug.Conn.html#resp/3) function:

https://github.com/dwyl/auth_plug/blob/e279438b13e4ec6453e9c1f18410d3df4ce9c91a/lib/auth_plug.ex#L83-L98

I'm currently using the logout function then redirecting to another page, however without using `put_status(conn, 302)` the redirection returns the default Phoenix redirection page because the status code is 200:

```elixir
def logout(conn, _params) do
  conn
  |> AuthPlug.logout()
  |> put_status(302) # add staus code to 302
  |> redirect(to: "/")                                                                                                                                                               
end            
```

So I'm wondering if we can just remove the `resp(conn, 200)` line in the `logout` function and let the consumer apps reply what they want (200, redirection,...)?

**Comment by nelsonic** [comment]
@SimonLab good question. Thanks for opening this issue. 🙌
I did a bit of searching when writing that line but don’t think I captured it anywhere… 🤦‍♂️
happy to remove the line now that we have an issue to reference. 👍🏻

**Comment by SimonLab** [comment]
Thanks for checking the issue @nelsonic I've just created a PR to remove it, I don't think it should break any other applications but I will keep an eye. And if necessary we can add it back

**Comment by nelsonic** [comment]
PR #47 merged. 👍🏻
Package published to https://hex.pm/packages/auth_plug/1.4.10 📦 
(Thanks again @SimonLab)
