### ISSUE TITLE
Exporting env variable appears erronous 

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/auth_plug#75]
I'm following through using this plug and it appears to work correctly, thank you very much!

However, during my implementation, I only seemed to get it working when I was using `https://auth.dwyl.com/ ` instead of the deployed Heroku app, as written in README. 

Additionally, after creating my own app inside `auth.dwyl.com`, this plug only worked when I exported the variable WITHOUT the  `/auth.dwyl.com` portion of the text for it to work.

<img width="806" alt="Screenshot 2022-10-13 at 15 44 03" src="https://user-images.githubusercontent.com/17494745/195628748-f90b30b1-74f6-4a4f-80a7-2b85315ec45e.png">

Otherwise, I got a `:signature_error` from this plug every time I tried to sign in with GitHub.

I can make a PR to fix the README file with these changes if you want to, just give me a heads-up if my walkthrough is a valid one.

**Comment by nelsonic** [comment]
@LuchoTurtle can you please confirm which **`version`** of **`auth_plug`** you were attempting this with?
The domain in this case **`auth.dwyl.com`** at the end of the API Key should be required ...

https://github.com/dwyl/auth_plug/blob/f2856128b30503599d3ad76da788e61e67e209ce/lib/token.ex#L54-L60

Used in:

https://github.com/dwyl/auth_plug/blob/f2856128b30503599d3ad76da788e61e67e209ce/lib/auth_plug.ex#L152-L165

Invoked by:

https://github.com/dwyl/auth_plug/blob/f2856128b30503599d3ad76da788e61e67e209ce/lib/auth_plug.ex#L57-L71

**Comment by LuchoTurtle** [comment]
Forgot to also comment here. I was using a *previous version* but while I was attempting to use the latest, it broke. This is related to #76

**Comment by nelsonic** [comment]
Please try: https://authdemo.fly.dev/

**Comment by LuchoTurtle** [comment]
Gonna have a look at this after the https://github.com/dwyl/product-roadmap/issues/40 Flutter preliminary repos and [`Edit Timers`](https://github.com/dwyl/mvp/tree/edit-timer) are properly merged 👍

**Comment by LuchoTurtle** [comment]
The work done in https://github.com/dwyl/phoenix-liveview-realtime-cursor-tracking-tutorial/pull/12 shows that this issue is now resolved.

Closing it. Thanks!
