### ISSUE TITLE
Create Helper Method for adding `person` and `loggedin` to `socket` `assigns`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth_plug#86]
As noted in https://github.com/dwyl/auth_plug/pull/84#issuecomment-1319873162 we currently have to add the `person` and `loggedin` _manually_ in `LiveView` Apps. This is obviously an undesirable step and creates duplicated (non-DRY) code in several of our example/tutorial projects e.g: 

https://github.com/dwyl/mvp/blob/0270bb5b610496197a5d28dd87bbb7412745663e/lib/app_web/controllers/auth_controller.ex#L12-L15

# Todo

+ [x] Create a helper function that accepts the `jwt` and `socket` and returns the socket with the 

i.e. executes the following:

```sh
def assign_jwt_to_socket(jwt, socket) do
    claims =
      jwt
      |> AuthPlug.Token.verify_jwt!()
      |> AuthPlug.Helpers.strip_struct_metadata()
      |> Useful.atomize_map_keys()

    socket =
      socket
      |> assign_new(:person, fn -> claims end)
      |> assign_new(:loggedin, fn -> true end)
end
```

That way in any `LiveView` App that uses `auth_plug` this is a 1-liner. 

# Edit:

Decided to alter the `assign_jwt_to_socket/3` function signature to the following: 

```elixir
  def assign_jwt_to_socket(socket, assign_new, jwt) do
    claims =
      jwt
      |> AuthPlug.Token.verify_jwt!()
      |> AuthPlug.Helpers.strip_struct_metadata()
      |> Useful.atomize_map_keys()

    socket =
      socket
      # Pass function by reference in Elixir:
      # stackoverflow.com/a/22562288/1148249
      |> assign_new.(:person, fn -> claims end)
      |> assign_new.(:loggedin, fn -> true end)

    socket
  end
```

Having `socket` as the first argument ensures that it is "chainable" e.g:

```elixir
socket = socket
  |> AuthPlug.assign_jwt_to_socket(&Phoenix.LiveView.assign_new/3, jwt)
  |> assign_new(:another_param, fn -> true end)
```

**Comment by nelsonic** [comment]
Not quite finished. Going to continue on my branch: https://github.com/dwyl/auth_plug/pull/89

**Comment by LuchoTurtle** [comment]
After finishing, if you could tag me after publishing the new version to `hex` would be great so I know I have the green light to finish https://github.com/dwyl/phoenix-liveview-realtime-cursor-tracking-tutorial/pull/12#discussion_r1030924516

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/auth_plug/1.5.1 📦 🚀

**Comment by nelsonic** [comment]
@LuchoTurtle please review/merge: https://github.com/dwyl/auth_plug/pull/89
Then Proceed back to: https://github.com/dwyl/phoenix-liveview-realtime-cursor-tracking-tutorial/pull/12/files#r1030924516 🙏

**Comment by LuchoTurtle** [comment]
Merged. 
Thanks for publishing 👍
